### ISSUE TITLE
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

### ISSUE THREAD

**Issue by abdoelsayed2016** [deepcodebase/inpaint#1]
Dear sir,
I appreciate your work but I got this error even I followed all the steps 

╭─────────────────────────────────── Config ───────────────────────────────────╮
│     1 model:                                                                              │
│     2   _target_: model.dfnet.DFNet                                          │
│     3   c_img: 3                                                             │
│     4   c_mask: 1                                                            │
│     5   c_alpha: 3                                                           │
│     6   mode: nearest                                                        │
│     7   norm: batch                                                          │
│     8   act_en: relu                                                         │
│     9   act_de: leaky_relu                                                   │
│    10   en_ksize:                                                            │
│    11   - 7                                                                  │
│    12   - 5                                                                  │
│    13   - 5                                                                  │
│    14   - 3                                                                  │
│    15   - 3                                                                  │
│    16   - 3                                                                  │
│    17   - 3                                                                  │
│    18   - 3                                                                  │
│    19   de_ksize:                                                            │
│    20   - 3                                                                  │
│    21   - 3                                                                  │
│    22   - 3                                                                  │
│    23   - 3                                                                  │
│    24   - 3                                                                  │
│    25   - 3                                                                  │
│    26   - 3                                                                  │
│    27   - 3                                                                  │
│    28   blend_layers:                                                        │
│    29   - 0                                                                  │
│    30   - 1                                                                  │
│    31   - 2                                                                  │
│    32   - 3                                                                  │
│    33   - 4                                                                  │
│    34   - 5                                                                  │
│    35 loss:                                                                  │
│    36   _target_: loss.InpaintLoss                                           │
│    37   c_img: 3                                                             │
│    38   w_l1: 6.0                                                            │
│    39   w_percep: 0.1                                                        │
│    40   w_style: 240.0                                                       │
│    41   w_tv: 0.1                                                            │
│    42   structure_layers:                                                    │
│    43   - 0                                                                  │
│    44   - 1                                                                  │
│    45   - 2                                                                  │
│    46   - 3                                                                  │
│    47   - 4                                                                  │
│    48   - 5                                                                  │
│    49   texture_layers:                                                      │
│    50   - 0                                                                  │
│    51   - 1                                                                  │
│    52   - 2                                                                  │
│    53 optim:                                                                 │
│    54   _target_: torch.optim.AdamW                                          │
│    55   lr: 0.002                                                            │
│    56 scheduler:                                                             │
│    57   _target_: torch.optim.lr_scheduler.CosineAnnealingLR                 │
│    58   T_max: 20                                                            │
│    59 dataset:                                                               │
│    60   _target_: dataset.inpaint.InpaintDataModule                          │
│    61   name: places2                                                        │
│    62   data:                                                                │
│    63     train_dir: /data/places2/data_large                                │
│    64     val_dir: /data/places2/data_large                                  │
│    65     test_dir: /data/places2/test_large                                 │
│    66   mask:                                                                │
│    67     train_dir: /data/mask                                              │
│    68     val_dir: /data/mask                                                │
│    69     test_dir: /data/mask                                               │
│    70   batch_size: 32                                                       │
│    71   num_workers: 4                                                       │
│    72   pin_memory: true                                                     │
│    73 pipeline:                                                              │
│    74   _target_: pipeline.inpainter.LitInpainter                            │
│    75 callbacks:                                                             │
│    76   checkpoint:                                                          │
│    77     _target_: pytorch_lightning.callbacks.ModelCheckpoint              │
│    78     dirpath: log/checkpoints                                           │
│    79     filename: '{epoch}-{step}-{val_loss:.2f}'                          │
│    80     save_last: true                                                    │
│    81     monitor: val_loss                                                  │
│    82     save_top_k: 2                                                      │
│    83     verbose: true                                                      │
│    84     mode: min                                                          │
│    85   lr_monitor:                                                          │
│    86     _target_: pytorch_lightning.callbacks.LearningRateMonitor          │
│    87 mode: debug                                                            │
│    88 pl_trainer:                                                            │
│    89   accelerator: ddp                                                     │
│    90   precision: 16                                                        │
│    91   amp_backend: native                                                  │
│    92   amp_level: O2                                                        │
│    93   profiler: simple                                                     │
│    94   weights_summary: top                                                 │
│    95   deterministic: true                                                  │
│    96   max_epochs: 20                                                       │
│    97   gpus: -1                                                             │
│    98   default_root_dir: ./                                                 │
│    99 val_save:                                                              │
│   100   n_image_per_batch: 8                                                 │
│   101   n_save: 11                                                           │
│   102 run_test: false                                                        │
│   103 seed: 2021                                                             │
│   104 find_unused_parameters: true                                           │
│   105                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯

[2021-08-12 22:08:09,938][pytorch_lightning.utilities.seed][INFO] - Global seed set to 2021
[2021-08-12 22:08:11,047][pytorch_lightning.utilities.distributed][INFO] - GPU available: True, used: True
[2021-08-12 22:08:11,047][pytorch_lightning.utilities.distributed][INFO] - TPU available: None, using: 0 TPU cores
[2021-08-12 22:08:11,047][pytorch_lightning.trainer.connectors.accelerator_connector][INFO] - Using native 16bit precision.
[2021-08-12 22:08:11,053][pytorch_lightning.accelerators.gpu][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[2021-08-12 22:08:11,054][pytorch_lightning.loggers.tensorboard][WARNING] - Missing logger folder: ./lightning_logs
[2021-08-12 22:08:11,056][pytorch_lightning.utilities.seed][INFO] - Global seed set to 2021
[2021-08-12 22:08:11,056][pytorch_lightning.plugins.training_type.ddp][INFO] - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
[2021-08-12 22:08:11,057][root][INFO] - Added key: store_based_barrier_key:1 to store for rank: 0
[2021-08-12 22:08:12,914][pytorch_lightning.core.lightning][INFO] - 
  | Name  | Type        | Params
--------------------------------------
0 | model | DFNet       | 32.9 M
1 | loss  | InpaintLoss | 1.7 M 
--------------------------------------
32.9 M    Trainable params
1.7 M     Non-trainable params
34.6 M    Total params
138.464   Total estimated model params size (MB)
Error executing job with overrides: []
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 36, in main
    trainer.fit(model, datamodule)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 846, in run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 364, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 325, in _reset_eval_dataloader
    num_batches = len(dataloader) if has_len(dataloader) else float('inf')
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py", line 33, in has_len
    raise ValueError('`Dataloader` returned 0 length. Please make sure that it returns at least 1 batch')
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

**Comment by hughplay** [comment]
Do you place your `Places2` data correctly?
If correct, you should see `/data/places2` inside your docker container.

**Comment by hughplay** [comment]
`README.md` has been updated. Hope it helps. : )

**Comment by abdoelsayed2016** [comment]
i solved the problem by place the folder, not inside the data in the main directory
